use calc_expr::BuildError;
use calc_syntax::{NotationConflict, NotationMode, ParseErrorKind};

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LoadErrorKind {
    NotUtf8,
    UnexpectedPath,
    MissingTitle,
    TitleDoesNotMatchPath,
    MalformedSection,
    DuplicateSection,
    UnknownSection(String),
    UnclosedBlock,
    BlockOutsideSection,
    UnexpectedText,
    DuplicateKey(String),
    UnknownKey(String),
    MissingKey(String),
    EmptyValue(String),
    InvalidIdentifier(String),
    InvalidCorpusId(String),
    DuplicateIdentifier(String),
    RetiredIdentifier(String),
    UnknownConcept(String),
    UnknownSource(String),
    UnknownRole(String),
    UnknownObject(String),
    RoleOfAnotherObject(String),
    UnknownQuantityKind(String),
    InvalidDimension(String),
    InvalidYear(String),
    UnknownRelationKind(String),
    MissingFormula,
    UnexpectedBlockCount {
        expected: usize,
        found: usize,
    },
    FormulaNotAFunction,
    ParameterCountMismatch {
        expected: usize,
        found: usize,
    },
    Formula(ParseErrorKind),
    Build(BuildError),
    MissingEnglishText(String),
    PrerequisiteCycle(String),
    UnsupportedContent,
    InvalidLocale(String),
    UnknownGroup(String),
    GroupWithoutSection(String),
    ConceptNotInCurriculum(String),
    PrerequisiteNotEarlier {
        concept: String,
        prerequisite: String,
    },
    InvalidNotationHeading(String),
    InvalidModeValue {
        mode: NotationMode,
        value: String,
    },
    NoNotation,
    NotationConflict(NotationConflict),
    SourcesDiffer(String),
    NotationVersionGap(String),
    NotationFromDiffers(String),
    SharedFromGroup(String),
    NoNotationForFirstGroup,
    NotationReadsLess {
        notation: String,
        mode: NotationMode,
    },
    ShippedNotationMissing(String),
    ShippedNotationChanged(String),
    InvalidDisplayUnit(String),
    DisplayUnitOfOtherDimension {
        kind: String,
        unit: String,
    },
    CompoundNotAllowed(String),
    CompoundNotDescending(String),
    CompoundNotAlone(String),
    ScaleNotAlone(String),
    DisplayedListNotAscending(String),
    DisplayedListMixesPi(String),
    DuplicateUnitSection(String),
    UnitStageOutsideCurriculum(String),
    UnknownUnitSystem(String),
    InvalidRecognized(String),
    UnknownRelation(String),
    ReservedParameter(String),
    DuplicateParameter(String),
    FreeNameInPattern(String),
    UnusedPatternVariable(String),
    PatternIsVariable,
    DuplicatePattern {
        pattern: String,
        way: String,
    },
    UnclosedValue,
    ValueWithoutPlaces(String),
    InvalidPlaces(String),
    ValueNotANumber(String),
    ValueIsExact(String),
    RoundingUndecided(String),
    TypedDecimal(String),
    TypedApproximation,
    MissingNotation(String),
    UnknownDecimalMark(String),
    InvalidStart(String),
    UndeclaredBeginning(String),
    BeginningWithPrerequisites(String),
    UnknownActivityKind(String),
    UnknownActivityShape(String),
    UnknownActivityVariation(String),
    TooFewActivityShapes(usize),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LoadError {
    pub file: String,
    pub line: usize,
    pub kind: LoadErrorKind,
}
